/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.fei.view;

import br.edu.fei.controller.Controller;
import javax.swing.JTable;

/**
 *
 * @author Pichau
 */
public class curtidosView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(curtidosView.class.getName());

    private Controller controller;
    
    public void setControllerCurtidos(Controller controller){
        this.controller = controller;
    }
    

    /**
     * Creates new form curtidosView
     */
    public curtidosView() {

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCurtidas = new javax.swing.JTable();
        Botao_voltar_filmes = new javax.swing.JButton();
        Descurtir_Filmes = new javax.swing.JButton();
        Fundo_titulo = new javax.swing.JDesktopPane();
        Titulo_curtidas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaCurtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id do filme", "Nome", "Produtora", "Descricao"
            }
        ));
        jScrollPane1.setViewportView(tabelaCurtidas);

        Botao_voltar_filmes.setText("Voltar");
        Botao_voltar_filmes.addActionListener(this::Botao_voltar_filmesActionPerformed);

        Descurtir_Filmes.setText("Descurtir Filme");
        Descurtir_Filmes.addActionListener(this::Descurtir_FilmesActionPerformed);

        Titulo_curtidas.setText("TABELA CURTIDAS");

        Fundo_titulo.setLayer(Titulo_curtidas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Fundo_tituloLayout = new javax.swing.GroupLayout(Fundo_titulo);
        Fundo_titulo.setLayout(Fundo_tituloLayout);
        Fundo_tituloLayout.setHorizontalGroup(
            Fundo_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Fundo_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_tituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Titulo_curtidas)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Fundo_tituloLayout.setVerticalGroup(
            Fundo_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(Fundo_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_tituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Titulo_curtidas)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo_titulo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_voltar_filmes)
                        .addGap(389, 389, 389)
                        .addComponent(Descurtir_Filmes)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fundo_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descurtir_Filmes)
                    .addComponent(Botao_voltar_filmes))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Descurtir_FilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descurtir_FilmesActionPerformed
if (controller != null) {
        controller.acaoDescurtir();
    } else {
        System.err.println("Erro: O controller não foi inicializado no JFrame!");
        // Opcional: mostrar um aviso na tela
        javax.swing.JOptionPane.showMessageDialog(this, "Erro interno: Controller nulo.");
    }// TODO add your handling code here:
    }//GEN-LAST:event_Descurtir_FilmesActionPerformed

    private void Botao_voltar_filmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_voltar_filmesActionPerformed
            this.dispose();
            controller.abrirFilmes();
    }//GEN-LAST:event_Botao_voltar_filmesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_voltar_filmes;
    private javax.swing.JButton Descurtir_Filmes;
    private javax.swing.JDesktopPane Fundo_titulo;
    private javax.swing.JLabel Titulo_curtidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCurtidas;
    // End of variables declaration//GEN-END:variables

    
public JTable getTabelaCurtidos() {
    return tabelaCurtidas;
}
}
