/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.fei.view;

import br.edu.fei.controller.Controller;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Pichau
 */
public class Filmes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Filmes.class.getName());

    private Controller controller;
    
    public void setControllerLista(Controller controller){
        this.controller = controller;
    }
    /**
     * Creates new form Filmes
     */
    public Filmes() {
        initComponents();
       
        tabelaFilmes.setSelectionMode(
        javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo = new javax.swing.JPanel();
        Fundo_Titulo = new javax.swing.JDesktopPane();
        Titulo_Filmes = new javax.swing.JLabel();
        Botao_Curtir = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFilmes = new javax.swing.JTable();
        Botao_Tabela_Curtidas = new javax.swing.JButton();
        Favoritar = new javax.swing.JButton();
        Botao_pesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo_Filmes.setText("Filmes Disponiveis");

        Fundo_Titulo.setLayer(Titulo_Filmes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Fundo_TituloLayout = new javax.swing.GroupLayout(Fundo_Titulo);
        Fundo_Titulo.setLayout(Fundo_TituloLayout);
        Fundo_TituloLayout.setHorizontalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Titulo_Filmes)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Fundo_TituloLayout.setVerticalGroup(
            Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(Fundo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fundo_TituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Titulo_Filmes)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Botao_Curtir.setText("Curtir filme selecionado");
        Botao_Curtir.addActionListener(this::Botao_CurtirActionPerformed);

        tabelaFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Produtora", "descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFilmes);

        scrollTabela.setViewportView(jScrollPane1);

        Botao_Tabela_Curtidas.setText("Ir para curtidas");
        Botao_Tabela_Curtidas.addActionListener(this::Botao_Tabela_CurtidasActionPerformed);

        Favoritar.setText("Criar Playlist");
        Favoritar.addActionListener(this::FavoritarActionPerformed);

        Botao_pesquisa.setText("Pesquisar playlist");
        Botao_pesquisa.addActionListener(this::Botao_pesquisaActionPerformed);

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo_Titulo)
            .addGroup(FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addComponent(Botao_Curtir)
                        .addGap(80, 80, 80)
                        .addComponent(Botao_Tabela_Curtidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Favoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(Botao_pesquisa)))
                .addContainerGap())
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addComponent(Fundo_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Favoritar)
                            .addComponent(Botao_Tabela_Curtidas)))
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Botao_pesquisa)
                            .addComponent(Botao_Curtir))))
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Fundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_CurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_CurtirActionPerformed

    controller.acaoCurtir();

    this.dispose();

    controller.abrirCurtidos();
    }//GEN-LAST:event_Botao_CurtirActionPerformed

    private void Botao_Tabela_CurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Tabela_CurtidasActionPerformed
            this.dispose();
            controller.abrirCurtidos();// TODO add your handling code here:
    }//GEN-LAST:event_Botao_Tabela_CurtidasActionPerformed

    private void FavoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritarActionPerformed
        controller.acaoCriarPlaylist();// TODO add your handling code here:
    }//GEN-LAST:event_FavoritarActionPerformed

    private void Botao_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_pesquisaActionPerformed
        controller.acaoPesquisarPlaylist();// TODO add your handling code here:
    }//GEN-LAST:event_Botao_pesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Filmes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Curtir;
    private javax.swing.JButton Botao_Tabela_Curtidas;
    private javax.swing.JButton Botao_pesquisa;
    private javax.swing.JButton Favoritar;
    private javax.swing.JPanel Fundo;
    private javax.swing.JDesktopPane Fundo_Titulo;
    private javax.swing.JLabel Titulo_Filmes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tabelaFilmes;
    // End of variables declaration//GEN-END:variables
private void mostrarFilmesAction(java.awt.event.ActionEvent evt) {
        this.controller.carregarTabelaFilmes();
        System.out.println("O botão foi clicado!"); 
    }
public JTable getTabelaFilmes() {
    return tabelaFilmes;
}

}
